### ISSUE TITLE
Video can't not play on safari MacOS

### ISSUE THREAD

**Issue by anhnvme** [animedoodee/JwPlayer-for-drivestream#5]
Hello,

Do u know why video can't play on Safari in Mac and iPhone ?
Chrome, Firefox is ok

**Comment by animedoodee** [comment]
i don't know why video can't play on iOS

**Comment by anhnvme** [comment]
i see this code can play at mobile and mac but it not showing low quality link
https://github.com/ArdiArtani/Google-Drive-Player-Script
You can look into it

Thanks you so much

**Comment by animedoodee** [comment]
I will try to fix it >,<
